CREATE DOMAIN descricao varchar(100) not null;

CREATE TABLE USUARIO(
  ID_USUARIO INTEGER NOT NULL,
  NOME descricao,
  SENHA VARCHAR(30) NOT NULL,
  TIPO  VARCHAR(30) NOT NULL,
  CADASTRO date NOT NULL,
  constraint PK_USUARIO PRIMARY KEY(ID_USUARIO));

CREATE TABLE EMPRESA(
ID_EMPRESA INTEGER NOT null,
RAZAO_SOCIAL descricao,
N_FANTASIA descricao,
ENDERECO descricao,
NUMERO INTEGER NOT NULL,
BAIRRO descricao,
CIDADE descricao,
UF CHAR(2) NOT NULL,
TELEFONE VARCHAR(15) NOT null,
CPF_CNPJ VARCHAR(20) NOT null, 
EMAIL DESCRICAO,
CADASTRO DATE NOT null,
constraint PK_EMPRESA PRIMARY KEY(ID_EMPRESA)
);

CREATE TABLE FORNECEDOR(
ID_FORNECEDOR INTEGER NOT NULL,
NOME descricao,
ENDERECO descricao,
NUMERO INTEGER NOT NULL,
BAIRRO descricao,
CIDADE descricao,
UF CHAR(2) NOT NULL,
CEP VARCHAR(16)NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
CNPJ VARCHAR(20) NOT NULL,
EMAIL descricao, 
CADASTRO DATE NOT NULL,
constraint PK_FORNECEDOR primary key(ID_FORNECEDOR)
);

create TABLE CLIENTE(
ID_CLIENTE INTEGER NOT NULL,
NOME descricao,
ENDERECO descricao,
NUMERO integer NOT NULL,
BAIRRO DESCRICAO,
CIDADE descricao,
UF CHAR(2) NOT null, 
CEP varchar(16) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
CPF varchar(20) NOT NULL,
EMAIL descricao,
CADASTRO DATE NOT NULL,
constraint PK_CLIENTE PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE PRODUTO(
ID_PRODUTO INTEGER NOT NULL,
DESCRICAO       descricao,
ID_FORNECEDOR   INTEGER NOT NULL,
VL_CUSTO        decimal(11,2) NOT null,
VL_VENDA        DECIMAL(11,2) NOT NULL,
ESTOQUE         DECIMAL(11,2) NOT NULL,
ESTOQUE_MIN     DECIMAL(11,2) NOT NULL,
UNIDADE         VARCHAR(6),
CADASTTRO       DATE NOT NULL,
constraint PK_PRODUTO PRIMARY KEY(ID_PRODUTO),
constraint FK_FORNECEDOR_PRODUTO foreign KEY(ID_FORNECEDOR) references fornecedor(ID_FORNECEDOR)
);

CREATE TABLE FORMA_PGTO(
ID_FORMA_PGTO integer NOT NULL,
DESCRICAO descricao,
CADASTRO DATE NOT null, 
constraint PK_FORMA_PGTO primary key(ID_FORMA_PGTO)
);

create table COMPRA (
ID_COMPRA INTEGER NOT NULL,
ID_FORNECEDOR INTEGER NOT NULL,
ID_FORMA_PGTO INTEGER NOT NULL,
usuario descricao,
VALOR decimal(11,2) NOT NULL,
CADASTRO DATE NOT NULL,
constraint PK_COMPRA PRIMARY key(ID_COMPRA),
constraint FK_FORMA_PGTO_COMPRA foreign KEY(ID_FORMA_PGTO) references forma_pgto(ID_FORMA_PGTO),
constraint FK_FORNECEDOR_COMPRA foreign key(ID_FORNECEDOR) references fornecedor(ID_FORNECEDOR)
);

CREATE TABLE ITEM_COMPRA(
SEQUENCIA INTEGER NOT NULL,
ID_COMPRA INTEGER NOT NULL,
ID_PRODUTO integer NOT NULL,
QTDE DECIMAL(11,2) NOT NULL,
VL_CUSTO DECIMAL(11,2) NOT NULL,
DESCONTO DECIMAL(11,2),
TOTAL_ITEM DECIMAL(11,2),
constraint PK_ITEM_COMPRA primary key(SEQUENCIA, ID_COMPRA),
constraint FK_COMPRA_ITEM_COMPRA foreign key(ID_COMPRA) references compra(ID_COMPRA),
constraint FK_PRODUTO_ITEM_COMPRA foreign key(ID_PRODUTO) references produto(ID_PRODUTO) ON DELETE CASCADE
);

CREATE TABLE CONTAS_PAGAR(
SEQUENCIA INTEGER NOT null,
ID_COMPRA INTEGER NOT null, 
VALOR_PARCELA decimal NOT NULL,
VENCIMENTO DATE not NULL,
DT_PAGAMENTO DATE,
ATRASO INTEGER,
JUROS DECIMAL(11,2),
VL_JUROS DECIMAL(11,2),
TOTAL_PAGAR DECIMAL(11,2),
STATUS VARCHAR(10),
constraint PK_CONTAS_PAGAR PRIMARY KEY(SEQUENCIA, ID_COMPRA),
constraint FK_CONTAS_PAGAR_COMPRA foreign KEY(ID_COMPRA) references COMPRA(ID_COMPRA)ON DELETE CASCADE
);

create table VENDA (
ID_VENDA INTEGER NOT NULL,
ID_CLIENTE INTEGER NOT NULL,
ID_FORMA_PGTO INTEGER NOT NULL,
usuario descricao,
VALOR decimal(11,2) NOT NULL,
CADASTRO DATE NOT NULL,
constraint PK_VENDA PRIMARY key(ID_VENDA),
constraint FK_FORMA_PGTO_VENDA foreign KEY(ID_FORMA_PGTO) references forma_pgto(ID_FORMA_PGTO),
constraint FK_CLIENTE_VENDA foreign key(ID_CLIENTE) references CLIENTE(ID_CLIENTE)
);

CREATE TABLE ITEM_VENDA(
SEQUENCIA INTEGER NOT NULL,
ID_VENDA INTEGER NOT NULL,
ID_PRODUTO integer NOT NULL,
QTDE DECIMAL(11,2) NOT NULL,
VL_CUSTO DECIMAL(11,2) NOT NULL,
DESCONTO DECIMAL(11,2),
TOTAL_ITEM DECIMAL(11,2),
constraint PK_ITEM_VENDA primary key(SEQUENCIA, ID_VENDA),
constraint FK_VENDA_ITEM_VENDA foreign key(ID_VENDA) references VENDA(ID_VENDA),
constraint FK_PRODUTO_ITEM_VENDA foreign key(ID_PRODUTO) references produto(ID_PRODUTO) ON DELETE CASCADE
);

CREATE TABLE CONTAS_RECEBER(
SEQUENCIA INTEGER NOT null,
ID_VENDA INTEGER NOT null,
VALOR_PARCELA decimal NOT NULL,
VENCIMENTO DATE not NULL,
DT_PAGAMENTO DATE,
ATRASO INTEGER,
JUROS DECIMAL(11,2),
VL_JUROS DECIMAL(11,2),
TOTAL_PAGAR DECIMAL(11,2),
STATUS VARCHAR(10),
constraint PK_CONTAS_RECEBER PRIMARY KEY(SEQUENCIA, ID_VENDA),
constraint FK_CONTAS_RECEBER_VENDA foreign KEY(ID_VENDA) references VENDA(ID_VENDA)ON DELETE CASCADE
);
